CREATE TABLE IF NOT EXISTS Users (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	username VARCHAR(128) NOT NULL UNIQUE check (length(username) > 1),
	password VARCHAR(32) NOT NULL check (length(password) >= 8 and password REGEXP '[^a-zA-Z0-9]'),
	email VARCHAR(64) NOT NULL check (email like '%@%')
);


CREATE TABLE IF NOT EXISTS orders (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL ,
	product_id BIGINT UNSIGNED NOT NULL ,
	count INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS products (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE check (length(name) >= 2),
	cost INTEGER NOT NULL,
	count INTEGER NOT NULL,
	seller_id BIGINT UNSIGNED
);


CREATE TABLE IF NOT EXISTS `seller` (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	company VARCHAR(64) NOT NULL,
	phone VARCHAR(32) check (length(phone) >= 7)
);


ALTER TABLE orders
ADD FOREIGN KEY(user_id) REFERENCES Users(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE orders
ADD FOREIGN KEY(product_id) REFERENCES products(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE products
ADD FOREIGN KEY(seller_id) REFERENCES seller(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;






